# Site Settings
title: 'å¿µ'
description: 'Anything is possible'
url: 'https://whoisnian.com'
baseurl: ''

# Building Settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# paginate
paginate: 10

# excerpt
excerpt_separator: '<!-- more -->'
